export const GENERATED_COMMENT = `/**
 * THIS FILE IS GENERATED - DO NOT MODIFY DIRECTLY
 * Generated by @saka-labsonrpc/jsonrpc-generator
 * 
 * @generated
 */`;

export const GENERATED_COMMENT_WITH_OPENAPI_TS_CREDIT = `/**
 * THIS FILE IS GENERATED - DO NOT MODIFY DIRECTLY
 * Generated by @saka-labsonrpc/jsonrpc-generator with credit to openapi-typescript <3
 * 
 * @generated
 */`;
