/**
 * THIS FILE IS GENERATED - DO NOT MODIFY DIRECTLY
 * Generated by @saka-labsonrpc/jsonrpc-generator
 * 
 * @generated
 */
import { z } from "zod/v4";

export const AccessKeySchema = z.object({
    nonce: z.number(),
    permission: z.lazy(() => AccessKeyPermissionSchema)
});
export const AccessKeyCreationConfigViewSchema = z.object({
    fullAccessCost: z.lazy(() => FeeSchema),
    functionCallCost: z.lazy(() => FeeSchema),
    functionCallCostPerByte: z.lazy(() => FeeSchema)
});
export const AccessKeyInfoViewSchema = z.object({
    accessKey: z.lazy(() => AccessKeyViewSchema),
    publicKey: z.lazy(() => PublicKeySchema)
});
export const AccessKeyListSchema = z.object({
    keys: z.array(AccessKeyInfoViewSchema)
});
export const AccessKeyPermissionSchema = z.union([z.object({
    FunctionCall: z.lazy(() => FunctionCallPermissionSchema)
}), z.literal("FullAccess")]);
export const AccessKeyPermissionViewSchema = z.union([z.literal("FullAccess"), z.object({
    FunctionCall: z.object({
        allowance: z.union([z.string(), z.null()]).optional(),
        methodNames: z.array(z.string()),
        receiverId: z.string()
    })
})]);
export const AccessKeyViewSchema = z.object({
    nonce: z.number(),
    permission: AccessKeyPermissionViewSchema
});
export const AccountCreationConfigViewSchema = z.object({
    minAllowedTopLevelAccountLength: z.number(),
    registrarAccountId: z.lazy(() => AccountIdSchema)
});
export const AccountDataViewSchema = z.object({
    accountKey: z.lazy(() => PublicKeySchema),
    peerId: z.lazy(() => PublicKeySchema),
    proxies: z.array(z.lazy(() => Tier1ProxyViewSchema)),
    timestamp: z.string()
});
export const AccountIdSchema = z.string();
export const AccountIdValidityRulesVersionSchema = z.number();
export const AccountInfoSchema = z.object({
    accountId: AccountIdSchema,
    amount: z.string(),
    publicKey: z.lazy(() => PublicKeySchema)
});
export const AccountViewSchema = z.object({
    amount: z.string(),
    codeHash: z.lazy(() => CryptoHashSchema),
    globalContractAccountId: z.union([AccountIdSchema, z.null()]).optional(),
    globalContractHash: z.union([z.lazy(() => CryptoHashSchema), z.null()]).optional(),
    locked: z.string(),
    storagePaidAt: z.number(),
    storageUsage: z.number()
});
export const AccountWithPublicKeySchema = z.object({
    accountId: AccountIdSchema,
    publicKey: z.lazy(() => PublicKeySchema)
});
export const ActionCreationConfigViewSchema = z.object({
    addKeyCost: AccessKeyCreationConfigViewSchema,
    createAccountCost: z.lazy(() => FeeSchema),
    delegateCost: z.lazy(() => FeeSchema),
    deleteAccountCost: z.lazy(() => FeeSchema),
    deleteKeyCost: z.lazy(() => FeeSchema),
    deployContractCost: z.lazy(() => FeeSchema),
    deployContractCostPerByte: z.lazy(() => FeeSchema),
    functionCallCost: z.lazy(() => FeeSchema),
    functionCallCostPerByte: z.lazy(() => FeeSchema),
    stakeCost: z.lazy(() => FeeSchema),
    transferCost: z.lazy(() => FeeSchema)
});
export const ActionErrorSchema = z.object({
    index: z.union([z.number(), z.null()]).optional(),
    kind: z.lazy(() => ActionErrorKindSchema)
});
export const ActionErrorKindSchema = z.union([z.object({
    AccountAlreadyExists: z.object({
        accountId: AccountIdSchema
    })
}), z.object({
    AccountDoesNotExist: z.object({
        accountId: AccountIdSchema
    })
}), z.object({
    CreateAccountOnlyByRegistrar: z.object({
        accountId: AccountIdSchema,
        predecessorId: AccountIdSchema,
        registrarAccountId: AccountIdSchema
    })
}), z.object({
    CreateAccountNotAllowed: z.object({
        accountId: AccountIdSchema,
        predecessorId: AccountIdSchema
    })
}), z.object({
    ActorNoPermission: z.object({
        accountId: AccountIdSchema,
        actorId: AccountIdSchema
    })
}), z.object({
    DeleteKeyDoesNotExist: z.object({
        accountId: AccountIdSchema,
        publicKey: z.lazy(() => PublicKeySchema)
    })
}), z.object({
    AddKeyAlreadyExists: z.object({
        accountId: AccountIdSchema,
        publicKey: z.lazy(() => PublicKeySchema)
    })
}), z.object({
    DeleteAccountStaking: z.object({
        accountId: AccountIdSchema
    })
}), z.object({
    LackBalanceForState: z.object({
        accountId: AccountIdSchema,
        amount: z.string()
    })
}), z.object({
    TriesToUnstake: z.object({
        accountId: AccountIdSchema
    })
}), z.object({
    TriesToStake: z.object({
        accountId: AccountIdSchema,
        balance: z.string(),
        locked: z.string(),
        stake: z.string()
    })
}), z.object({
    InsufficientStake: z.object({
        accountId: AccountIdSchema,
        minimumStake: z.string(),
        stake: z.string()
    })
}), z.object({
    FunctionCallError: z.lazy(() => FunctionCallErrorSchema)
}), z.object({
    NewReceiptValidationError: z.lazy(() => ReceiptValidationErrorSchema)
}), z.object({
    OnlyImplicitAccountCreationAllowed: z.object({
        accountId: AccountIdSchema
    })
}), z.object({
    DeleteAccountWithLargeState: z.object({
        accountId: AccountIdSchema
    })
}), z.literal("DelegateActionInvalidSignature"), z.object({
    DelegateActionSenderDoesNotMatchTxReceiver: z.object({
        receiverId: AccountIdSchema,
        senderId: AccountIdSchema
    })
}), z.literal("DelegateActionExpired"), z.object({
    DelegateActionAccessKeyError: z.lazy(() => InvalidAccessKeyErrorSchema)
}), z.object({
    DelegateActionInvalidNonce: z.object({
        akNonce: z.number(),
        delegateNonce: z.number()
    })
}), z.object({
    DelegateActionNonceTooLarge: z.object({
        delegateNonce: z.number(),
        upperBound: z.number()
    })
}), z.object({
    GlobalContractDoesNotExist: z.object({
        identifier: z.lazy(() => GlobalContractIdentifierSchema)
    })
})]);
export const ActionsValidationErrorSchema = z.union([z.literal("DeleteActionMustBeFinal"), z.object({
    TotalPrepaidGasExceeded: z.object({
        limit: z.number(),
        totalPrepaidGas: z.number()
    })
}), z.object({
    TotalNumberOfActionsExceeded: z.object({
        limit: z.number(),
        totalNumberOfActions: z.number()
    })
}), z.object({
    AddKeyMethodNamesNumberOfBytesExceeded: z.object({
        limit: z.number(),
        totalNumberOfBytes: z.number()
    })
}), z.object({
    AddKeyMethodNameLengthExceeded: z.object({
        length: z.number(),
        limit: z.number()
    })
}), z.literal("IntegerOverflow"), z.object({
    InvalidAccountId: z.object({
        accountId: z.string()
    })
}), z.object({
    ContractSizeExceeded: z.object({
        limit: z.number(),
        size: z.number()
    })
}), z.object({
    FunctionCallMethodNameLengthExceeded: z.object({
        length: z.number(),
        limit: z.number()
    })
}), z.object({
    FunctionCallArgumentsLengthExceeded: z.object({
        length: z.number(),
        limit: z.number()
    })
}), z.object({
    UnsuitableStakingKey: z.object({
        publicKey: z.lazy(() => PublicKeySchema)
    })
}), z.literal("FunctionCallZeroAttachedGas"), z.literal("DelegateActionMustBeOnlyOne"), z.object({
    UnsupportedProtocolFeature: z.object({
        protocolFeature: z.string(),
        version: z.number()
    })
})]);
export const ActionViewSchema = z.union([z.literal("CreateAccount"), z.object({
    DeployContract: z.object({
        code: z.string()
    })
}), z.object({
    FunctionCall: z.object({
        args: z.lazy(() => FunctionArgsSchema),
        deposit: z.string(),
        gas: z.number(),
        methodName: z.string()
    })
}), z.object({
    Transfer: z.object({
        deposit: z.string()
    })
}), z.object({
    Stake: z.object({
        publicKey: z.lazy(() => PublicKeySchema),
        stake: z.string()
    })
}), z.object({
    AddKey: z.object({
        accessKey: AccessKeyViewSchema,
        publicKey: z.lazy(() => PublicKeySchema)
    })
}), z.object({
    DeleteKey: z.object({
        publicKey: z.lazy(() => PublicKeySchema)
    })
}), z.object({
    DeleteAccount: z.object({
        beneficiaryId: AccountIdSchema
    })
}), z.object({
    Delegate: z.object({
        delegateAction: z.lazy(() => DelegateActionSchema),
        signature: z.lazy(() => SignatureSchema)
    })
}), z.object({
    DeployGlobalContract: z.object({
        code: z.string()
    })
}), z.object({
    DeployGlobalContractByAccountId: z.object({
        code: z.string()
    })
}), z.object({
    UseGlobalContract: z.object({
        codeHash: z.lazy(() => CryptoHashSchema)
    })
}), z.object({
    UseGlobalContractByAccountId: z.object({
        accountId: AccountIdSchema
    })
})]);
export const AddKeyActionSchema = z.object({
    accessKey: AccessKeySchema,
    publicKey: z.lazy(() => PublicKeySchema)
});
export const BandwidthRequestSchema = z.object({
    requestedValuesBitmap: z.lazy(() => BandwidthRequestBitmapSchema),
    toShard: z.number()
});
export const BandwidthRequestBitmapSchema = z.object({
    data: z.array(z.number())
});
export const BandwidthRequestsSchema = z.object({
    V1: z.lazy(() => BandwidthRequestsV1Schema)
});
export const BandwidthRequestsV1Schema = z.object({
    requests: z.array(BandwidthRequestSchema)
});
export const BlockHeaderInnerLiteViewSchema = z.object({
    blockMerkleRoot: z.lazy(() => CryptoHashSchema),
    epochId: z.lazy(() => CryptoHashSchema),
    height: z.number(),
    nextBpHash: z.lazy(() => CryptoHashSchema),
    nextEpochId: z.lazy(() => CryptoHashSchema),
    outcomeRoot: z.lazy(() => CryptoHashSchema),
    prevStateRoot: z.lazy(() => CryptoHashSchema),
    timestamp: z.number(),
    timestampNanosec: z.string()
});
export const BlockHeaderViewSchema = z.object({
    approvals: z.array(z.union([z.lazy(() => SignatureSchema), z.null()])),
    blockBodyHash: z.union([z.lazy(() => CryptoHashSchema), z.null()]).optional(),
    blockMerkleRoot: z.lazy(() => CryptoHashSchema),
    blockOrdinal: z.union([z.number(), z.null()]).optional(),
    challengesResult: z.array(z.lazy(() => SlashedValidatorSchema)),
    challengesRoot: z.lazy(() => CryptoHashSchema),
    chunkEndorsements: z.union([z.array(z.array(z.number())), z.null()]).optional(),
    chunkHeadersRoot: z.lazy(() => CryptoHashSchema),
    chunkMask: z.array(z.boolean()),
    chunkReceiptsRoot: z.lazy(() => CryptoHashSchema),
    chunkTxRoot: z.lazy(() => CryptoHashSchema),
    chunksIncluded: z.number(),
    epochId: z.lazy(() => CryptoHashSchema),
    epochSyncDataHash: z.union([z.lazy(() => CryptoHashSchema), z.null()]).optional(),
    gasPrice: z.string(),
    hash: z.lazy(() => CryptoHashSchema),
    height: z.number(),
    lastDsFinalBlock: z.lazy(() => CryptoHashSchema),
    lastFinalBlock: z.lazy(() => CryptoHashSchema),
    latestProtocolVersion: z.number(),
    nextBpHash: z.lazy(() => CryptoHashSchema),
    nextEpochId: z.lazy(() => CryptoHashSchema),
    outcomeRoot: z.lazy(() => CryptoHashSchema),
    prevHash: z.lazy(() => CryptoHashSchema),
    prevHeight: z.union([z.number(), z.null()]).optional(),
    prevStateRoot: z.lazy(() => CryptoHashSchema),
    randomValue: z.lazy(() => CryptoHashSchema),
    rentPaid: z.string(),
    signature: z.lazy(() => SignatureSchema),
    timestamp: z.number(),
    timestampNanosec: z.string(),
    totalSupply: z.string(),
    validatorProposals: z.array(z.lazy(() => ValidatorStakeViewSchema)),
    validatorReward: z.string()
});
export const BlockIdSchema = z.union([z.number(), z.lazy(() => CryptoHashSchema)]);
export const BlockStatusViewSchema = z.object({
    hash: z.lazy(() => CryptoHashSchema),
    height: z.number()
});
export const CallResultSchema = z.object({
    logs: z.array(z.string()),
    result: z.array(z.number())
});
export const CatchupStatusViewSchema = z.object({
    blocksToCatchup: z.array(BlockStatusViewSchema),
    shardSyncStatus: z.record(z.string(), z.unknown()),
    syncBlockHash: z.lazy(() => CryptoHashSchema),
    syncBlockHeight: z.number()
});
export const ChunkDistributionNetworkConfigSchema = z.object({
    enabled: z.boolean(),
    uris: z.lazy(() => ChunkDistributionUrisSchema)
});
export const ChunkDistributionUrisSchema = z.object({
    get: z.string(),
    set: z.string()
});
export const ChunkHeaderViewSchema = z.object({
    balanceBurnt: z.string(),
    bandwidthRequests: z.union([BandwidthRequestsSchema, z.null()]).optional(),
    chunkHash: z.lazy(() => CryptoHashSchema),
    congestionInfo: z.union([z.lazy(() => CongestionInfoViewSchema), z.null()]).optional(),
    encodedLength: z.number(),
    encodedMerkleRoot: z.lazy(() => CryptoHashSchema),
    gasLimit: z.number(),
    gasUsed: z.number(),
    heightCreated: z.number(),
    heightIncluded: z.number(),
    outcomeRoot: z.lazy(() => CryptoHashSchema),
    outgoingReceiptsRoot: z.lazy(() => CryptoHashSchema),
    prevBlockHash: z.lazy(() => CryptoHashSchema),
    prevStateRoot: z.lazy(() => CryptoHashSchema),
    rentPaid: z.string(),
    shardId: z.lazy(() => ShardIdSchema),
    signature: z.lazy(() => SignatureSchema),
    txRoot: z.lazy(() => CryptoHashSchema),
    validatorProposals: z.array(z.lazy(() => ValidatorStakeViewSchema)),
    validatorReward: z.string()
});
export const CompilationErrorSchema = z.union([z.object({
    CodeDoesNotExist: z.object({
        accountId: AccountIdSchema
    })
}), z.object({
    PrepareError: z.lazy(() => PrepareErrorSchema)
}), z.object({
    WasmerCompileError: z.object({
        msg: z.string()
    })
})]);
export const CongestionControlConfigViewSchema = z.object({
    allowedShardOutgoingGas: z.number(),
    maxCongestionIncomingGas: z.number(),
    maxCongestionMemoryConsumption: z.number(),
    maxCongestionMissedChunks: z.number(),
    maxCongestionOutgoingGas: z.number(),
    maxOutgoingGas: z.number(),
    maxTxGas: z.number(),
    minOutgoingGas: z.number(),
    minTxGas: z.number(),
    outgoingReceiptsBigSizeLimit: z.number(),
    outgoingReceiptsUsualSizeLimit: z.number(),
    rejectTxCongestionThreshold: z.number()
});
export const CongestionInfoViewSchema = z.object({
    allowedShard: z.number(),
    bufferedReceiptsGas: z.string(),
    delayedReceiptsGas: z.string(),
    receiptBytes: z.number()
});
export const ContractCodeViewSchema = z.object({
    codeBase64: z.string(),
    hash: z.lazy(() => CryptoHashSchema)
});
export const CostGasUsedSchema = z.object({
    cost: z.string(),
    costCategory: z.string(),
    gasUsed: z.string()
});
export const CreateAccountActionSchema = z.record(z.string(), z.unknown());
export const CryptoHashSchema = z.string();
export const CurrentEpochValidatorInfoSchema = z.object({
    accountId: AccountIdSchema,
    isSlashed: z.boolean(),
    numExpectedBlocks: z.number(),
    numExpectedChunks: z.number(),
    numExpectedChunksPerShard: z.array(z.number()),
    numExpectedEndorsements: z.number(),
    numExpectedEndorsementsPerShard: z.array(z.number()),
    numProducedBlocks: z.number(),
    numProducedChunks: z.number(),
    numProducedChunksPerShard: z.array(z.number()),
    numProducedEndorsements: z.number(),
    numProducedEndorsementsPerShard: z.array(z.number()),
    publicKey: z.lazy(() => PublicKeySchema),
    shards: z.array(z.lazy(() => ShardIdSchema)),
    shardsEndorsed: z.array(z.lazy(() => ShardIdSchema)),
    stake: z.string()
});
export const DataReceiptCreationConfigViewSchema = z.object({
    baseCost: z.lazy(() => FeeSchema),
    costPerByte: z.lazy(() => FeeSchema)
});
export const DataReceiverViewSchema = z.object({
    dataId: CryptoHashSchema,
    receiverId: AccountIdSchema
});
export const DelegateActionSchema = z.object({
    actions: z.array(z.lazy(() => NonDelegateActionSchema)),
    maxBlockHeight: z.number(),
    nonce: z.number(),
    publicKey: z.lazy(() => PublicKeySchema),
    receiverId: AccountIdSchema,
    senderId: AccountIdSchema
});
export const DeleteAccountActionSchema = z.object({
    beneficiaryId: AccountIdSchema
});
export const DeleteKeyActionSchema = z.object({
    publicKey: z.lazy(() => PublicKeySchema)
});
export const DeployContractActionSchema = z.object({
    code: z.string()
});
export const DeployGlobalContractActionSchema = z.object({
    code: z.string(),
    deployMode: z.lazy(() => GlobalContractDeployModeSchema)
});
export const DetailedDebugStatusSchema = z.object({
    blockProductionDelayMillis: z.number(),
    catchupStatus: z.array(CatchupStatusViewSchema),
    currentHeadStatus: BlockStatusViewSchema,
    currentHeaderHeadStatus: BlockStatusViewSchema,
    networkInfo: z.lazy(() => NetworkInfoViewSchema),
    syncStatus: z.string()
});
export const DirectionSchema = z.union([z.literal("Left"), z.literal("Right")]);
export const DumpConfigSchema = z.object({
    credentialsFile: z.union([z.string(), z.null()]).optional(),
    iterationDelay: z.union([z.lazy(() => DurationAsStdSchemaProviderSchema), z.null()]).optional(),
    location: z.lazy(() => ExternalStorageLocationSchema),
    restartDumpForShards: z.union([z.array(z.lazy(() => ShardIdSchema)), z.null()]).optional()
});
export const DurationAsStdSchemaProviderSchema = z.object({
    nanos: z.number(),
    secs: z.number()
});
export const EpochIdSchema = CryptoHashSchema;
export const EpochSyncConfigSchema = z.object({
    disableEpochSyncForBootstrapping: z.boolean(),
    epochSyncHorizon: z.number(),
    ignoreEpochSyncNetworkRequests: z.boolean(),
    timeoutForEpochSync: DurationAsStdSchemaProviderSchema
});
export const ExecutionMetadataViewSchema = z.object({
    gasProfile: z.union([z.array(CostGasUsedSchema), z.null()]).optional(),
    version: z.number()
});
export const ExecutionOutcomeViewSchema = z.object({
    executorId: AccountIdSchema,
    gasBurnt: z.number(),
    logs: z.array(z.string()),
    metadata: ExecutionMetadataViewSchema,
    receiptIds: z.array(CryptoHashSchema),
    status: z.lazy(() => ExecutionStatusViewSchema),
    tokensBurnt: z.string()
});
export const ExecutionOutcomeWithIdViewSchema = z.object({
    blockHash: CryptoHashSchema,
    id: CryptoHashSchema,
    outcome: ExecutionOutcomeViewSchema,
    proof: z.array(z.lazy(() => MerklePathItemSchema))
});
export const ExecutionStatusViewSchema = z.union([z.literal("Unknown"), z.object({
    Failure: z.lazy(() => TxExecutionErrorSchema)
}), z.object({
    SuccessValue: z.string()
}), z.object({
    SuccessReceiptId: CryptoHashSchema
})]);
export const ExtCostsConfigViewSchema = z.object({
    altBn128G1MultiexpBase: z.number(),
    altBn128G1MultiexpElement: z.number(),
    altBn128G1SumBase: z.number(),
    altBn128G1SumElement: z.number(),
    altBn128PairingCheckBase: z.number(),
    altBn128PairingCheckElement: z.number(),
    base: z.number(),
    bls12381G1MultiexpBase: z.number(),
    bls12381G1MultiexpElement: z.number(),
    bls12381G2MultiexpBase: z.number(),
    bls12381G2MultiexpElement: z.number(),
    bls12381MapFpToG1Base: z.number(),
    bls12381MapFpToG1Element: z.number(),
    bls12381MapFp2ToG2Base: z.number(),
    bls12381MapFp2ToG2Element: z.number(),
    bls12381P1DecompressBase: z.number(),
    bls12381P1DecompressElement: z.number(),
    bls12381P1SumBase: z.number(),
    bls12381P1SumElement: z.number(),
    bls12381P2DecompressBase: z.number(),
    bls12381P2DecompressElement: z.number(),
    bls12381P2SumBase: z.number(),
    bls12381P2SumElement: z.number(),
    bls12381PairingBase: z.number(),
    bls12381PairingElement: z.number(),
    contractCompileBase: z.number(),
    contractCompileBytes: z.number(),
    contractLoadingBase: z.number(),
    contractLoadingBytes: z.number(),
    ecrecoverBase: z.number(),
    ed25519VerifyBase: z.number(),
    ed25519VerifyByte: z.number(),
    keccak256Base: z.number(),
    keccak256Byte: z.number(),
    keccak512Base: z.number(),
    keccak512Byte: z.number(),
    logBase: z.number(),
    logByte: z.number(),
    promiseAndBase: z.number(),
    promiseAndPerPromise: z.number(),
    promiseReturn: z.number(),
    readCachedTrieNode: z.number(),
    readMemoryBase: z.number(),
    readMemoryByte: z.number(),
    readRegisterBase: z.number(),
    readRegisterByte: z.number(),
    ripemd160Base: z.number(),
    ripemd160Block: z.number(),
    sha256Base: z.number(),
    sha256Byte: z.number(),
    storageHasKeyBase: z.number(),
    storageHasKeyByte: z.number(),
    storageIterCreateFromByte: z.number(),
    storageIterCreatePrefixBase: z.number(),
    storageIterCreatePrefixByte: z.number(),
    storageIterCreateRangeBase: z.number(),
    storageIterCreateToByte: z.number(),
    storageIterNextBase: z.number(),
    storageIterNextKeyByte: z.number(),
    storageIterNextValueByte: z.number(),
    storageLargeReadOverheadBase: z.number(),
    storageLargeReadOverheadByte: z.number(),
    storageReadBase: z.number(),
    storageReadKeyByte: z.number(),
    storageReadValueByte: z.number(),
    storageRemoveBase: z.number(),
    storageRemoveKeyByte: z.number(),
    storageRemoveRetValueByte: z.number(),
    storageWriteBase: z.number(),
    storageWriteEvictedByte: z.number(),
    storageWriteKeyByte: z.number(),
    storageWriteValueByte: z.number(),
    touchingTrieNode: z.number(),
    utf8DecodingBase: z.number(),
    utf8DecodingByte: z.number(),
    utf16DecodingBase: z.number(),
    utf16DecodingByte: z.number(),
    validatorStakeBase: z.number(),
    validatorTotalStakeBase: z.number(),
    writeMemoryBase: z.number(),
    writeMemoryByte: z.number(),
    writeRegisterBase: z.number(),
    writeRegisterByte: z.number(),
    yieldCreateBase: z.number(),
    yieldCreateByte: z.number(),
    yieldResumeBase: z.number(),
    yieldResumeByte: z.number()
});
export const ExternalStorageConfigSchema = z.object({
    externalStorageFallbackThreshold: z.number(),
    location: z.lazy(() => ExternalStorageLocationSchema),
    numConcurrentRequests: z.number(),
    numConcurrentRequestsDuringCatchup: z.number()
});
export const ExternalStorageLocationSchema = z.union([z.object({
    S3: z.object({
        bucket: z.string(),
        region: z.string()
    })
}), z.object({
    Filesystem: z.object({
        rootDir: z.string()
    })
}), z.object({
    GCS: z.object({
        bucket: z.string()
    })
})]);
export const FeeSchema = z.object({
    execution: z.number(),
    sendNotSir: z.number(),
    sendSir: z.number()
});
export const FinalExecutionOutcomeViewSchema = z.object({
    receiptsOutcome: z.array(ExecutionOutcomeWithIdViewSchema),
    status: z.lazy(() => FinalExecutionStatusSchema),
    transaction: z.lazy(() => SignedTransactionViewSchema),
    transactionOutcome: ExecutionOutcomeWithIdViewSchema
});
export const FinalExecutionOutcomeWithReceiptViewSchema = z.object({
    receipts: z.array(z.lazy(() => ReceiptViewSchema)),
    receiptsOutcome: z.array(ExecutionOutcomeWithIdViewSchema),
    status: z.lazy(() => FinalExecutionStatusSchema),
    transaction: z.lazy(() => SignedTransactionViewSchema),
    transactionOutcome: ExecutionOutcomeWithIdViewSchema
});
export const FinalExecutionStatusSchema = z.union([z.literal("NotStarted"), z.literal("Started"), z.object({
    Failure: z.lazy(() => TxExecutionErrorSchema)
}), z.object({
    SuccessValue: z.string()
})]);
export const FinalitySchema = z.union([z.literal("optimistic"), z.literal("near-final"), z.literal("final")]);
export const FunctionArgsSchema = z.string();
export const FunctionCallActionSchema = z.object({
    args: z.string(),
    deposit: z.string(),
    gas: z.number(),
    methodName: z.string()
});
export const FunctionCallErrorSchema = z.union([z.union([z.literal("WasmUnknownError"), z.literal("_EVMError")]), z.object({
    CompilationError: CompilationErrorSchema
}), z.object({
    LinkError: z.object({
        msg: z.string()
    })
}), z.object({
    MethodResolveError: z.lazy(() => MethodResolveErrorSchema)
}), z.object({
    WasmTrap: z.lazy(() => WasmTrapSchema)
}), z.object({
    HostError: z.lazy(() => HostErrorSchema)
}), z.object({
    ExecutionError: z.string()
})]);
export const FunctionCallPermissionSchema = z.object({
    allowance: z.union([z.string(), z.null()]).optional(),
    methodNames: z.array(z.string()),
    receiverId: z.string()
});
export const GasKeyViewSchema = z.object({
    balance: z.number(),
    numNonces: z.number(),
    permission: AccessKeyPermissionViewSchema
});
export const GCConfigSchema = z.object({
    gcBlocksLimit: z.number(),
    gcForkCleanStep: z.number(),
    gcNumEpochsToKeep: z.number(),
    gcStepPeriod: DurationAsStdSchemaProviderSchema
});
export const GenesisConfigSchema = z.object({
    avgHiddenValidatorSeatsPerShard: z.array(z.number()),
    blockProducerKickoutThreshold: z.number(),
    chainId: z.string(),
    chunkProducerAssignmentChangesLimit: z.number(),
    chunkProducerKickoutThreshold: z.number(),
    chunkValidatorOnlyKickoutThreshold: z.number(),
    dynamicResharding: z.boolean(),
    epochLength: z.number(),
    fishermenThreshold: z.string(),
    gasLimit: z.number(),
    gasPriceAdjustmentRate: z.array(z.number()),
    genesisHeight: z.number(),
    genesisTime: z.string(),
    maxGasPrice: z.string(),
    maxInflationRate: z.array(z.number()),
    maxKickoutStakePerc: z.number(),
    minGasPrice: z.string(),
    minimumStakeDivisor: z.number(),
    minimumStakeRatio: z.array(z.number()),
    minimumValidatorsPerShard: z.number(),
    numBlockProducerSeats: z.number(),
    numBlockProducerSeatsPerShard: z.array(z.number()),
    numBlocksPerYear: z.number(),
    numChunkOnlyProducerSeats: z.number(),
    numChunkProducerSeats: z.number(),
    numChunkValidatorSeats: z.number(),
    onlineMaxThreshold: z.array(z.number()),
    onlineMinThreshold: z.array(z.number()),
    protocolRewardRate: z.array(z.number()),
    protocolTreasuryAccount: AccountIdSchema,
    protocolUpgradeStakeThreshold: z.array(z.number()),
    protocolVersion: z.number(),
    shardLayout: z.lazy(() => ShardLayoutSchema),
    shuffleShardAssignmentForChunkProducers: z.boolean(),
    targetValidatorMandatesPerShard: z.number(),
    totalSupply: z.string(),
    transactionValidityPeriod: z.number(),
    useProductionConfig: z.boolean(),
    validators: z.array(AccountInfoSchema)
});
export const GenesisConfigRequestSchema = z.null();
export const GlobalContractDeployModeSchema = z.union([z.literal("CodeHash"), z.literal("AccountId")]);
export const GlobalContractIdentifierSchema = z.union([z.object({
    CodeHash: CryptoHashSchema
}), z.object({
    AccountId: AccountIdSchema
})]);
export const HostErrorSchema = z.union([z.literal("BadUTF16"), z.literal("BadUTF8"), z.literal("GasExceeded"), z.literal("GasLimitExceeded"), z.literal("BalanceExceeded"), z.literal("EmptyMethodName"), z.object({
    GuestPanic: z.object({
        panicMsg: z.string()
    })
}), z.literal("IntegerOverflow"), z.object({
    InvalidPromiseIndex: z.object({
        promiseIdx: z.number()
    })
}), z.literal("CannotAppendActionToJointPromise"), z.literal("CannotReturnJointPromise"), z.object({
    InvalidPromiseResultIndex: z.object({
        resultIdx: z.number()
    })
}), z.object({
    InvalidRegisterId: z.object({
        registerId: z.number()
    })
}), z.object({
    IteratorWasInvalidated: z.object({
        iteratorIndex: z.number()
    })
}), z.literal("MemoryAccessViolation"), z.object({
    InvalidReceiptIndex: z.object({
        receiptIndex: z.number()
    })
}), z.object({
    InvalidIteratorIndex: z.object({
        iteratorIndex: z.number()
    })
}), z.literal("InvalidAccountId"), z.literal("InvalidMethodName"), z.literal("InvalidPublicKey"), z.object({
    ProhibitedInView: z.object({
        methodName: z.string()
    })
}), z.object({
    NumberOfLogsExceeded: z.object({
        limit: z.number()
    })
}), z.object({
    KeyLengthExceeded: z.object({
        length: z.number(),
        limit: z.number()
    })
}), z.object({
    ValueLengthExceeded: z.object({
        length: z.number(),
        limit: z.number()
    })
}), z.object({
    TotalLogLengthExceeded: z.object({
        length: z.number(),
        limit: z.number()
    })
}), z.object({
    NumberPromisesExceeded: z.object({
        limit: z.number(),
        numberOfPromises: z.number()
    })
}), z.object({
    NumberInputDataDependenciesExceeded: z.object({
        limit: z.number(),
        numberOfInputDataDependencies: z.number()
    })
}), z.object({
    ReturnedValueLengthExceeded: z.object({
        length: z.number(),
        limit: z.number()
    })
}), z.object({
    ContractSizeExceeded: z.object({
        limit: z.number(),
        size: z.number()
    })
}), z.object({
    Deprecated: z.object({
        methodName: z.string()
    })
}), z.object({
    ECRecoverError: z.object({
        msg: z.string()
    })
}), z.object({
    AltBn128InvalidInput: z.object({
        msg: z.string()
    })
}), z.object({
    Ed25519VerifyInvalidInput: z.object({
        msg: z.string()
    })
})]);
export const InvalidAccessKeyErrorSchema = z.union([z.object({
    AccessKeyNotFound: z.object({
        accountId: AccountIdSchema,
        publicKey: z.lazy(() => PublicKeySchema)
    })
}), z.object({
    ReceiverMismatch: z.object({
        akReceiver: z.string(),
        txReceiver: AccountIdSchema
    })
}), z.object({
    MethodNameMismatch: z.object({
        methodName: z.string()
    })
}), z.literal("RequiresFullAccess"), z.object({
    NotEnoughAllowance: z.object({
        accountId: AccountIdSchema,
        allowance: z.string(),
        cost: z.string(),
        publicKey: z.lazy(() => PublicKeySchema)
    })
}), z.literal("DepositWithFunctionCall")]);
export const InvalidTxErrorSchema = z.union([z.object({
    InvalidAccessKeyError: InvalidAccessKeyErrorSchema
}), z.object({
    InvalidSignerId: z.object({
        signerId: z.string()
    })
}), z.object({
    SignerDoesNotExist: z.object({
        signerId: AccountIdSchema
    })
}), z.object({
    InvalidNonce: z.object({
        akNonce: z.number(),
        txNonce: z.number()
    })
}), z.object({
    NonceTooLarge: z.object({
        txNonce: z.number(),
        upperBound: z.number()
    })
}), z.object({
    InvalidReceiverId: z.object({
        receiverId: z.string()
    })
}), z.literal("InvalidSignature"), z.object({
    NotEnoughBalance: z.object({
        balance: z.string(),
        cost: z.string(),
        signerId: AccountIdSchema
    })
}), z.object({
    LackBalanceForState: z.object({
        amount: z.string(),
        signerId: AccountIdSchema
    })
}), z.literal("CostOverflow"), z.literal("InvalidChain"), z.literal("Expired"), z.object({
    ActionsValidation: ActionsValidationErrorSchema
}), z.object({
    TransactionSizeExceeded: z.object({
        limit: z.number(),
        size: z.number()
    })
}), z.literal("InvalidTransactionVersion"), z.object({
    StorageError: z.lazy(() => StorageErrorSchema)
}), z.object({
    ShardCongested: z.object({
        congestionLevel: z.number(),
        shardId: z.number()
    })
}), z.object({
    ShardStuck: z.object({
        missedChunks: z.number(),
        shardId: z.number()
    })
})]);
export const KnownProducerViewSchema = z.object({
    accountId: AccountIdSchema,
    nextHops: z.union([z.array(z.lazy(() => PublicKeySchema)), z.null()]).optional(),
    peerId: z.lazy(() => PublicKeySchema)
});
export const LightClientBlockLiteViewSchema = z.object({
    innerLite: BlockHeaderInnerLiteViewSchema,
    innerRestHash: CryptoHashSchema,
    prevBlockHash: CryptoHashSchema
});
export const LimitConfigSchema = z.object({
    accountIdValidityRulesVersion: AccountIdValidityRulesVersionSchema,
    initialMemoryPages: z.number(),
    maxActionsPerReceipt: z.number(),
    maxArgumentsLength: z.number(),
    maxContractSize: z.number(),
    maxElementsPerContractTable: z.union([z.number(), z.null()]).optional(),
    maxFunctionsNumberPerContract: z.union([z.number(), z.null()]).optional(),
    maxGasBurnt: z.number(),
    maxLengthMethodName: z.number(),
    maxLengthReturnedData: z.number(),
    maxLengthStorageKey: z.number(),
    maxLengthStorageValue: z.number(),
    maxLocalsPerContract: z.union([z.number(), z.null()]).optional(),
    maxMemoryPages: z.number(),
    maxNumberBytesMethodNames: z.number(),
    maxNumberInputDataDependencies: z.number(),
    maxNumberLogs: z.number(),
    maxNumberRegisters: z.number(),
    maxPromisesPerFunctionCallAction: z.number(),
    maxReceiptSize: z.number(),
    maxRegisterSize: z.number(),
    maxStackHeight: z.number(),
    maxTablesPerContract: z.union([z.number(), z.null()]).optional(),
    maxTotalLogLength: z.number(),
    maxTotalPrepaidGas: z.number(),
    maxTransactionSize: z.number(),
    maxYieldPayloadSize: z.number(),
    perReceiptStorageProofSizeLimit: z.number(),
    registersMemoryLimit: z.number(),
    yieldTimeoutLengthInBlocks: z.number()
});
export const LogSummaryStyleSchema = z.union([z.literal("plain"), z.literal("colored")]);
export const MerklePathItemSchema = z.object({
    direction: DirectionSchema,
    hash: CryptoHashSchema
});
export const MethodResolveErrorSchema = z.union([z.literal("MethodEmptyName"), z.literal("MethodNotFound"), z.literal("MethodInvalidSignature")]);
export const MissingTrieValueSchema = z.object({
    context: z.lazy(() => MissingTrieValueContextSchema),
    hash: CryptoHashSchema
});
export const MissingTrieValueContextSchema = z.union([z.literal("TrieIterator"), z.literal("TriePrefetchingStorage"), z.literal("TrieMemoryPartialStorage"), z.literal("TrieStorage")]);
export const MutableConfigValueSchema = z.string();
export const NetworkInfoViewSchema = z.object({
    connectedPeers: z.array(z.lazy(() => PeerInfoViewSchema)),
    knownProducers: z.array(KnownProducerViewSchema),
    numConnectedPeers: z.number(),
    peerMaxCount: z.number(),
    tier1AccountsData: z.array(AccountDataViewSchema),
    tier1AccountsKeys: z.array(z.lazy(() => PublicKeySchema)),
    tier1Connections: z.array(z.lazy(() => PeerInfoViewSchema))
});
export const NextEpochValidatorInfoSchema = z.object({
    accountId: AccountIdSchema,
    publicKey: z.lazy(() => PublicKeySchema),
    shards: z.array(z.lazy(() => ShardIdSchema)),
    stake: z.string()
});
export const NonDelegateActionSchema = z.union([z.object({
    CreateAccount: CreateAccountActionSchema
}), z.object({
    DeployContract: DeployContractActionSchema
}), z.object({
    FunctionCall: FunctionCallActionSchema
}), z.object({
    Transfer: z.lazy(() => TransferActionSchema)
}), z.object({
    Stake: z.lazy(() => StakeActionSchema)
}), z.object({
    AddKey: AddKeyActionSchema
}), z.object({
    DeleteKey: DeleteKeyActionSchema
}), z.object({
    DeleteAccount: DeleteAccountActionSchema
}), z.object({
    DeployGlobalContract: DeployGlobalContractActionSchema
}), z.object({
    UseGlobalContract: z.lazy(() => UseGlobalContractActionSchema)
})]);
export const PeerIdSchema = z.lazy(() => PublicKeySchema);
export const PeerInfoViewSchema = z.object({
    accountId: z.union([AccountIdSchema, z.null()]).optional(),
    addr: z.string(),
    archival: z.boolean(),
    blockHash: z.union([CryptoHashSchema, z.null()]).optional(),
    connectionEstablishedTimeMillis: z.number(),
    height: z.union([z.number(), z.null()]).optional(),
    isHighestBlockInvalid: z.boolean(),
    isOutboundPeer: z.boolean(),
    lastTimePeerRequestedMillis: z.number(),
    lastTimeReceivedMessageMillis: z.number(),
    nonce: z.number(),
    peerId: z.lazy(() => PublicKeySchema),
    receivedBytesPerSec: z.number(),
    sentBytesPerSec: z.number(),
    trackedShards: z.array(z.lazy(() => ShardIdSchema))
});
export const PrepareErrorSchema = z.union([z.literal("Serialization"), z.literal("Deserialization"), z.literal("InternalMemoryDeclared"), z.literal("GasInstrumentation"), z.literal("StackHeightInstrumentation"), z.literal("Instantiate"), z.literal("Memory"), z.literal("TooManyFunctions"), z.literal("TooManyLocals"), z.literal("TooManyTables"), z.literal("TooManyTableElements")]);
export const ProtocolVersionCheckConfigSchema = z.union([z.literal("Next"), z.literal("NextNext")]);
export const PublicKeySchema = z.string();
export const Range_of_uint64Schema = z.object({
    end: z.number(),
    start: z.number()
});
export const ReceiptEnumViewSchema = z.union([z.object({
    Action: z.object({
        actions: z.array(ActionViewSchema),
        gasPrice: z.string(),
        inputDataIds: z.array(CryptoHashSchema),
        isPromiseYield: z.boolean(),
        outputDataReceivers: z.array(DataReceiverViewSchema),
        signerId: AccountIdSchema,
        signerPublicKey: PublicKeySchema
    })
}), z.object({
    Data: z.object({
        data: z.union([z.string(), z.null()]),
        dataId: CryptoHashSchema,
        isPromiseResume: z.boolean()
    })
}), z.object({
    GlobalContractDistribution: z.object({
        alreadyDeliveredShards: z.array(z.lazy(() => ShardIdSchema)),
        code: z.string(),
        id: GlobalContractIdentifierSchema,
        targetShard: z.lazy(() => ShardIdSchema)
    })
})]);
export const ReceiptValidationErrorSchema = z.union([z.object({
    InvalidPredecessorId: z.object({
        accountId: z.string()
    })
}), z.object({
    InvalidReceiverId: z.object({
        accountId: z.string()
    })
}), z.object({
    InvalidSignerId: z.object({
        accountId: z.string()
    })
}), z.object({
    InvalidDataReceiverId: z.object({
        accountId: z.string()
    })
}), z.object({
    ReturnedValueLengthExceeded: z.object({
        length: z.number(),
        limit: z.number()
    })
}), z.object({
    NumberInputDataDependenciesExceeded: z.object({
        limit: z.number(),
        numberOfInputDataDependencies: z.number()
    })
}), z.object({
    ActionsValidation: ActionsValidationErrorSchema
}), z.object({
    ReceiptSizeExceeded: z.object({
        limit: z.number(),
        size: z.number()
    })
})]);
export const ReceiptViewSchema = z.object({
    predecessorId: AccountIdSchema,
    priority: z.number(),
    receipt: ReceiptEnumViewSchema,
    receiptId: CryptoHashSchema,
    receiverId: AccountIdSchema
});
export const RpcBlockRequestSchema = z.union([z.object({
    blockId: BlockIdSchema
}), z.object({
    finality: FinalitySchema
}), z.object({
    syncCheckpoint: z.lazy(() => SyncCheckpointSchema)
})]);
export const RpcBlockResponseSchema = z.object({
    author: AccountIdSchema,
    chunks: z.array(ChunkHeaderViewSchema),
    header: BlockHeaderViewSchema
});
export const RpcChunkRequestSchema = z.union([z.object({
    blockId: BlockIdSchema,
    shardId: z.lazy(() => ShardIdSchema)
}), z.object({
    chunkId: CryptoHashSchema
})]);
export const RpcChunkResponseSchema = z.object({
    author: AccountIdSchema,
    header: ChunkHeaderViewSchema,
    receipts: z.array(ReceiptViewSchema),
    transactions: z.array(z.lazy(() => SignedTransactionViewSchema))
});
export const RpcClientConfigRequestSchema = z.null();
export const RpcClientConfigResponseSchema = z.object({
    archive: z.boolean(),
    blockFetchHorizon: z.number(),
    blockHeaderFetchHorizon: z.number(),
    blockProductionTrackingDelay: z.array(z.number()),
    catchupStepPeriod: z.array(z.number()),
    chainId: z.string(),
    chunkDistributionNetwork: z.union([ChunkDistributionNetworkConfigSchema, z.null()]).optional(),
    chunkRequestRetryPeriod: z.array(z.number()),
    chunkValidationThreads: z.number(),
    chunkWaitMult: z.array(z.number()),
    clientBackgroundMigrationThreads: z.number(),
    doomslugStepPeriod: z.array(z.number()),
    enableMultilineLogging: z.boolean(),
    enableStatisticsExport: z.boolean(),
    epochLength: z.number(),
    epochSync: EpochSyncConfigSchema,
    expectedShutdown: MutableConfigValueSchema,
    gc: GCConfigSchema,
    headerSyncExpectedHeightPerSecond: z.number(),
    headerSyncInitialTimeout: z.array(z.number()),
    headerSyncProgressTimeout: z.array(z.number()),
    headerSyncStallBanTimeout: z.array(z.number()),
    logSummaryPeriod: z.array(z.number()),
    logSummaryStyle: LogSummaryStyleSchema,
    maxBlockProductionDelay: z.array(z.number()),
    maxBlockWaitDelay: z.array(z.number()),
    maxGasBurntView: z.union([z.number(), z.null()]).optional(),
    minBlockProductionDelay: z.array(z.number()),
    minNumPeers: z.number(),
    numBlockProducerSeats: z.number(),
    orphanStateWitnessMaxSize: z.number(),
    orphanStateWitnessPoolSize: z.number(),
    produceChunkAddTransactionsTimeLimit: z.string(),
    produceEmptyBlocks: z.boolean(),
    protocolVersionCheck: ProtocolVersionCheckConfigSchema,
    reshardingConfig: MutableConfigValueSchema,
    rpcAddr: z.union([z.string(), z.null()]).optional(),
    saveInvalidWitnesses: z.boolean(),
    saveLatestWitnesses: z.boolean(),
    saveTrieChanges: z.boolean(),
    saveTxOutcomes: z.boolean(),
    skipSyncWait: z.boolean(),
    stateRequestServerThreads: z.number(),
    stateRequestThrottlePeriod: z.array(z.number()),
    stateRequestsPerThrottlePeriod: z.number(),
    stateSync: z.lazy(() => StateSyncConfigSchema),
    stateSyncEnabled: z.boolean(),
    stateSyncExternalBackoff: z.array(z.number()),
    stateSyncExternalTimeout: z.array(z.number()),
    stateSyncP2pTimeout: z.array(z.number()),
    stateSyncRetryBackoff: z.array(z.number()),
    syncCheckPeriod: z.array(z.number()),
    syncHeightThreshold: z.number(),
    syncMaxBlockRequests: z.number(),
    syncStepPeriod: z.array(z.number()),
    trackedShardsConfig: z.lazy(() => TrackedShardsConfigSchema),
    transactionPoolSizeLimit: z.union([z.number(), z.null()]).optional(),
    transactionRequestHandlerThreads: z.number(),
    trieViewerStateSizeLimit: z.union([z.number(), z.null()]).optional(),
    ttlAccountIdRouter: z.array(z.number()),
    txRoutingHeightHorizon: z.number(),
    version: z.lazy(() => VersionSchema),
    viewClientThreads: z.number()
});
export const RpcCongestionLevelRequestSchema = z.union([z.object({
    blockId: BlockIdSchema,
    shardId: z.lazy(() => ShardIdSchema)
}), z.object({
    chunkId: CryptoHashSchema
})]);
export const RpcCongestionLevelResponseSchema = z.object({
    congestionLevel: z.number()
});
export const RpcErrorSchema = z.object({
    cause: z.unknown().optional(),
    code: z.number(),
    data: z.unknown().optional(),
    message: z.string(),
    name: z.unknown().optional()
}).and(z.union([z.object({
    cause: z.lazy(() => RpcRequestValidationErrorKindSchema),
    name: z.literal("REQUEST_VALIDATION_ERROR")
}), z.object({
    cause: z.unknown(),
    name: z.literal("HANDLER_ERROR")
}), z.object({
    cause: z.unknown(),
    name: z.literal("INTERNAL_ERROR")
})]));
export const RpcGasPriceRequestSchema = z.object({
    blockId: z.union([BlockIdSchema, z.null()]).optional()
});
export const RpcGasPriceResponseSchema = z.object({
    gasPrice: z.string()
});
export const RpcHealthRequestSchema = z.null();
export const RpcHealthResponseSchema = z.null();
export const RpcKnownProducerSchema = z.object({
    accountId: AccountIdSchema,
    addr: z.union([z.string(), z.null()]).optional(),
    peerId: PeerIdSchema
});
export const RpcLightClientBlockProofRequestSchema = z.object({
    blockHash: CryptoHashSchema,
    lightClientHead: CryptoHashSchema
});
export const RpcLightClientBlockProofResponseSchema = z.object({
    blockHeaderLite: LightClientBlockLiteViewSchema,
    blockProof: z.array(MerklePathItemSchema)
});
export const RpcLightClientExecutionProofRequestSchema = z.object({
    lightClientHead: CryptoHashSchema
}).and(z.union([z.object({
    senderId: AccountIdSchema,
    transactionHash: CryptoHashSchema,
    type: z.literal("transaction")
}), z.object({
    receiptId: CryptoHashSchema,
    receiverId: AccountIdSchema,
    type: z.literal("receipt")
})]));
export const RpcLightClientExecutionProofResponseSchema = z.object({
    blockHeaderLite: LightClientBlockLiteViewSchema,
    blockProof: z.array(MerklePathItemSchema),
    outcomeProof: ExecutionOutcomeWithIdViewSchema,
    outcomeRootProof: z.array(MerklePathItemSchema)
});
export const RpcLightClientNextBlockRequestSchema = z.object({
    lastBlockHash: CryptoHashSchema
});
export const RpcLightClientNextBlockResponseSchema = z.object({
    approvalsAfterNext: z.array(z.union([z.lazy(() => SignatureSchema), z.null()])).optional(),
    innerLite: BlockHeaderInnerLiteViewSchema.optional(),
    innerRestHash: CryptoHashSchema.optional(),
    nextBlockInnerHash: CryptoHashSchema.optional(),
    nextBps: z.union([z.array(z.lazy(() => ValidatorStakeViewSchema)), z.null()]).optional(),
    prevBlockHash: CryptoHashSchema.optional()
});
export const RpcMaintenanceWindowsRequestSchema = z.object({
    accountId: AccountIdSchema
});
export const RpcNetworkInfoRequestSchema = z.null();
export const RpcNetworkInfoResponseSchema = z.object({
    activePeers: z.array(z.lazy(() => RpcPeerInfoSchema)),
    knownProducers: z.array(RpcKnownProducerSchema),
    numActivePeers: z.number(),
    peerMaxCount: z.number(),
    receivedBytesPerSec: z.number(),
    sentBytesPerSec: z.number()
});
export const RpcPeerInfoSchema = z.object({
    accountId: z.union([AccountIdSchema, z.null()]).optional(),
    addr: z.union([z.string(), z.null()]).optional(),
    id: PeerIdSchema
});
export const RpcProtocolConfigRequestSchema = z.union([z.object({
    blockId: BlockIdSchema
}), z.object({
    finality: FinalitySchema
}), z.object({
    syncCheckpoint: z.lazy(() => SyncCheckpointSchema)
})]);
export const RpcProtocolConfigResponseSchema = z.object({
    avgHiddenValidatorSeatsPerShard: z.array(z.number()),
    blockProducerKickoutThreshold: z.number(),
    chainId: z.string(),
    chunkProducerKickoutThreshold: z.number(),
    chunkValidatorOnlyKickoutThreshold: z.number(),
    dynamicResharding: z.boolean(),
    epochLength: z.number(),
    fishermenThreshold: z.string(),
    gasLimit: z.number(),
    gasPriceAdjustmentRate: z.array(z.number()),
    genesisHeight: z.number(),
    genesisTime: z.string(),
    maxGasPrice: z.string(),
    maxInflationRate: z.array(z.number()),
    maxKickoutStakePerc: z.number(),
    minGasPrice: z.string(),
    minimumStakeDivisor: z.number(),
    minimumStakeRatio: z.array(z.number()),
    minimumValidatorsPerShard: z.number(),
    numBlockProducerSeats: z.number(),
    numBlockProducerSeatsPerShard: z.array(z.number()),
    numBlocksPerYear: z.number(),
    onlineMaxThreshold: z.array(z.number()),
    onlineMinThreshold: z.array(z.number()),
    protocolRewardRate: z.array(z.number()),
    protocolTreasuryAccount: AccountIdSchema,
    protocolUpgradeStakeThreshold: z.array(z.number()),
    protocolVersion: z.number(),
    runtimeConfig: z.lazy(() => RuntimeConfigViewSchema),
    shardLayout: z.lazy(() => ShardLayoutSchema),
    shuffleShardAssignmentForChunkProducers: z.boolean(),
    targetValidatorMandatesPerShard: z.number(),
    transactionValidityPeriod: z.number()
});
export const RpcQueryRequestSchema = z.union([z.object({
    blockId: BlockIdSchema
}).and(z.object({
    accountId: AccountIdSchema,
    requestType: z.literal("view_account")
})), z.object({
    blockId: BlockIdSchema
}).and(z.object({
    accountId: AccountIdSchema,
    requestType: z.literal("view_code")
})), z.object({
    blockId: BlockIdSchema
}).and(z.object({
    accountId: AccountIdSchema,
    includeProof: z.boolean().optional(),
    prefixBase64: z.lazy(() => StoreKeySchema),
    requestType: z.literal("view_state")
})), z.object({
    blockId: BlockIdSchema
}).and(z.object({
    accountId: AccountIdSchema,
    publicKey: PublicKeySchema,
    requestType: z.literal("view_access_key")
})), z.object({
    blockId: BlockIdSchema
}).and(z.object({
    accountId: AccountIdSchema,
    requestType: z.literal("view_access_key_list")
})), z.object({
    blockId: BlockIdSchema
}).and(z.object({
    accountId: AccountIdSchema,
    argsBase64: FunctionArgsSchema,
    methodName: z.string(),
    requestType: z.literal("call_function")
})), z.object({
    blockId: BlockIdSchema
}).and(z.object({
    codeHash: CryptoHashSchema,
    requestType: z.literal("view_global_contract_code")
})), z.object({
    blockId: BlockIdSchema
}).and(z.object({
    accountId: AccountIdSchema,
    requestType: z.literal("view_global_contract_code_by_account_id")
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    accountId: AccountIdSchema,
    requestType: z.literal("view_account")
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    accountId: AccountIdSchema,
    requestType: z.literal("view_code")
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    accountId: AccountIdSchema,
    includeProof: z.boolean().optional(),
    prefixBase64: z.lazy(() => StoreKeySchema),
    requestType: z.literal("view_state")
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    accountId: AccountIdSchema,
    publicKey: PublicKeySchema,
    requestType: z.literal("view_access_key")
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    accountId: AccountIdSchema,
    requestType: z.literal("view_access_key_list")
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    accountId: AccountIdSchema,
    argsBase64: FunctionArgsSchema,
    methodName: z.string(),
    requestType: z.literal("call_function")
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    codeHash: CryptoHashSchema,
    requestType: z.literal("view_global_contract_code")
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    accountId: AccountIdSchema,
    requestType: z.literal("view_global_contract_code_by_account_id")
})), z.object({
    syncCheckpoint: z.lazy(() => SyncCheckpointSchema)
}).and(z.object({
    accountId: AccountIdSchema,
    requestType: z.literal("view_account")
})), z.object({
    syncCheckpoint: z.lazy(() => SyncCheckpointSchema)
}).and(z.object({
    accountId: AccountIdSchema,
    requestType: z.literal("view_code")
})), z.object({
    syncCheckpoint: z.lazy(() => SyncCheckpointSchema)
}).and(z.object({
    accountId: AccountIdSchema,
    includeProof: z.boolean().optional(),
    prefixBase64: z.lazy(() => StoreKeySchema),
    requestType: z.literal("view_state")
})), z.object({
    syncCheckpoint: z.lazy(() => SyncCheckpointSchema)
}).and(z.object({
    accountId: AccountIdSchema,
    publicKey: PublicKeySchema,
    requestType: z.literal("view_access_key")
})), z.object({
    syncCheckpoint: z.lazy(() => SyncCheckpointSchema)
}).and(z.object({
    accountId: AccountIdSchema,
    requestType: z.literal("view_access_key_list")
})), z.object({
    syncCheckpoint: z.lazy(() => SyncCheckpointSchema)
}).and(z.object({
    accountId: AccountIdSchema,
    argsBase64: FunctionArgsSchema,
    methodName: z.string(),
    requestType: z.literal("call_function")
})), z.object({
    syncCheckpoint: z.lazy(() => SyncCheckpointSchema)
}).and(z.object({
    codeHash: CryptoHashSchema,
    requestType: z.literal("view_global_contract_code")
})), z.object({
    syncCheckpoint: z.lazy(() => SyncCheckpointSchema)
}).and(z.object({
    accountId: AccountIdSchema,
    requestType: z.literal("view_global_contract_code_by_account_id")
}))]);
export const RpcQueryResponseSchema = z.object({
    blockHash: CryptoHashSchema,
    blockHeight: z.number()
}).and(z.union([AccountViewSchema, ContractCodeViewSchema, z.lazy(() => ViewStateResultSchema), CallResultSchema, AccessKeyViewSchema, AccessKeyListSchema]));
export const RpcReceiptRequestSchema = z.object({
    receiptId: CryptoHashSchema
});
export const RpcReceiptResponseSchema = z.object({
    predecessorId: AccountIdSchema,
    priority: z.number(),
    receipt: ReceiptEnumViewSchema,
    receiptId: CryptoHashSchema,
    receiverId: AccountIdSchema
});
export const RpcRequestValidationErrorKindSchema = z.union([z.object({
    info: z.object({
        methodName: z.string()
    }),
    name: z.literal("METHOD_NOT_FOUND")
}), z.object({
    info: z.object({
        errorMessage: z.string()
    }),
    name: z.literal("PARSE_ERROR")
})]);
export const RpcSendTransactionRequestSchema = z.object({
    signedTxBase64: z.lazy(() => SignedTransactionSchema),
    waitUntil: z.lazy(() => TxExecutionStatusSchema)
});
export const RpcSplitStorageInfoRequestSchema = z.record(z.string(), z.unknown());
export const RpcSplitStorageInfoResponseSchema = z.object({
    coldHeadHeight: z.union([z.number(), z.null()]).optional(),
    finalHeadHeight: z.union([z.number(), z.null()]).optional(),
    headHeight: z.union([z.number(), z.null()]).optional(),
    hotDbKind: z.union([z.string(), z.null()]).optional()
});
export const RpcStateChangesInBlockByTypeRequestSchema = z.union([z.object({
    blockId: BlockIdSchema
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("account_changes")
})), z.object({
    blockId: BlockIdSchema
}).and(z.object({
    changesType: z.literal("single_access_key_changes"),
    keys: z.array(AccountWithPublicKeySchema)
})), z.object({
    blockId: BlockIdSchema
}).and(z.object({
    changesType: z.literal("single_gas_key_changes"),
    keys: z.array(AccountWithPublicKeySchema)
})), z.object({
    blockId: BlockIdSchema
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("all_access_key_changes")
})), z.object({
    blockId: BlockIdSchema
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("all_gas_key_changes")
})), z.object({
    blockId: BlockIdSchema
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("contract_code_changes")
})), z.object({
    blockId: BlockIdSchema
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("data_changes"),
    keyPrefixBase64: z.lazy(() => StoreKeySchema)
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("account_changes")
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    changesType: z.literal("single_access_key_changes"),
    keys: z.array(AccountWithPublicKeySchema)
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    changesType: z.literal("single_gas_key_changes"),
    keys: z.array(AccountWithPublicKeySchema)
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("all_access_key_changes")
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("all_gas_key_changes")
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("contract_code_changes")
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("data_changes"),
    keyPrefixBase64: z.lazy(() => StoreKeySchema)
})), z.object({
    syncCheckpoint: z.lazy(() => SyncCheckpointSchema)
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("account_changes")
})), z.object({
    syncCheckpoint: z.lazy(() => SyncCheckpointSchema)
}).and(z.object({
    changesType: z.literal("single_access_key_changes"),
    keys: z.array(AccountWithPublicKeySchema)
})), z.object({
    syncCheckpoint: z.lazy(() => SyncCheckpointSchema)
}).and(z.object({
    changesType: z.literal("single_gas_key_changes"),
    keys: z.array(AccountWithPublicKeySchema)
})), z.object({
    syncCheckpoint: z.lazy(() => SyncCheckpointSchema)
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("all_access_key_changes")
})), z.object({
    syncCheckpoint: z.lazy(() => SyncCheckpointSchema)
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("all_gas_key_changes")
})), z.object({
    syncCheckpoint: z.lazy(() => SyncCheckpointSchema)
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("contract_code_changes")
})), z.object({
    syncCheckpoint: z.lazy(() => SyncCheckpointSchema)
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("data_changes"),
    keyPrefixBase64: z.lazy(() => StoreKeySchema)
}))]);
export const RpcStateChangesInBlockByTypeResponseSchema = z.object({
    blockHash: CryptoHashSchema,
    changes: z.array(z.lazy(() => StateChangeKindViewSchema))
});
export const RpcStateChangesInBlockRequestSchema = z.union([z.object({
    blockId: BlockIdSchema
}), z.object({
    finality: FinalitySchema
}), z.object({
    syncCheckpoint: z.lazy(() => SyncCheckpointSchema)
})]);
export const RpcStateChangesInBlockResponseSchema = z.object({
    blockHash: CryptoHashSchema,
    changes: z.array(z.lazy(() => StateChangeWithCauseViewSchema))
});
export const RpcStatusRequestSchema = z.null();
export const RpcStatusResponseSchema = z.object({
    chainId: z.string(),
    detailedDebugStatus: z.union([DetailedDebugStatusSchema, z.null()]).optional(),
    genesisHash: CryptoHashSchema,
    latestProtocolVersion: z.number(),
    nodeKey: z.union([PublicKeySchema, z.null()]).optional(),
    nodePublicKey: PublicKeySchema,
    protocolVersion: z.number(),
    rpcAddr: z.union([z.string(), z.null()]).optional(),
    syncInfo: z.lazy(() => StatusSyncInfoSchema),
    uptimeSec: z.number(),
    validatorAccountId: z.union([AccountIdSchema, z.null()]).optional(),
    validatorPublicKey: z.union([PublicKeySchema, z.null()]).optional(),
    validators: z.array(z.lazy(() => ValidatorInfoSchema)),
    version: z.lazy(() => VersionSchema)
});
export const RpcTransactionResponseSchema = z.object({
    finalExecutionStatus: z.lazy(() => TxExecutionStatusSchema)
}).and(z.union([FinalExecutionOutcomeWithReceiptViewSchema, FinalExecutionOutcomeViewSchema]));
export const RpcTransactionStatusRequestSchema = z.object({
    waitUntil: z.lazy(() => TxExecutionStatusSchema)
}).and(z.union([z.object({
    signedTxBase64: z.lazy(() => SignedTransactionSchema)
}), z.object({
    senderAccountId: AccountIdSchema,
    txHash: CryptoHashSchema
})]));
export const RpcValidatorRequestSchema = z.union([z.literal("latest"), z.object({
    epochId: EpochIdSchema
}), z.object({
    blockId: BlockIdSchema
})]);
export const RpcValidatorResponseSchema = z.object({
    currentFishermen: z.array(z.lazy(() => ValidatorStakeViewSchema)),
    currentProposals: z.array(z.lazy(() => ValidatorStakeViewSchema)),
    currentValidators: z.array(CurrentEpochValidatorInfoSchema),
    epochHeight: z.number(),
    epochStartHeight: z.number(),
    nextFishermen: z.array(z.lazy(() => ValidatorStakeViewSchema)),
    nextValidators: z.array(NextEpochValidatorInfoSchema),
    prevEpochKickout: z.array(z.lazy(() => ValidatorKickoutViewSchema))
});
export const RpcValidatorsOrderedRequestSchema = z.object({
    blockId: z.union([BlockIdSchema, z.null()]).optional()
});
export const RuntimeConfigViewSchema = z.object({
    accountCreationConfig: AccountCreationConfigViewSchema,
    congestionControlConfig: CongestionControlConfigViewSchema,
    storageAmountPerByte: z.string(),
    transactionCosts: z.lazy(() => RuntimeFeesConfigViewSchema),
    wasmConfig: z.lazy(() => VMConfigViewSchema),
    witnessConfig: z.lazy(() => WitnessConfigViewSchema)
});
export const RuntimeFeesConfigViewSchema = z.object({
    actionCreationConfig: ActionCreationConfigViewSchema,
    actionReceiptCreationConfig: FeeSchema,
    burntGasReward: z.array(z.number()),
    dataReceiptCreationConfig: DataReceiptCreationConfigViewSchema,
    pessimisticGasPriceInflationRatio: z.array(z.number()),
    storageUsageConfig: z.lazy(() => StorageUsageConfigViewSchema)
});
export const ShardIdSchema = z.number();
export const ShardLayoutSchema = z.union([z.object({
    V0: z.lazy(() => ShardLayoutV0Schema)
}), z.object({
    V1: z.lazy(() => ShardLayoutV1Schema)
}), z.object({
    V2: z.lazy(() => ShardLayoutV2Schema)
})]);
export const ShardLayoutV0Schema = z.object({
    numShards: z.number(),
    version: z.number()
});
export const ShardLayoutV1Schema = z.object({
    boundaryAccounts: z.array(AccountIdSchema),
    shardsSplitMap: z.union([z.array(z.array(ShardIdSchema)), z.null()]).optional(),
    toParentShardMap: z.union([z.array(ShardIdSchema), z.null()]).optional(),
    version: z.number()
});
export const ShardLayoutV2Schema = z.object({
    boundaryAccounts: z.array(AccountIdSchema),
    idToIndexMap: z.record(z.string(), z.number()),
    indexToIdMap: z.record(z.string(), ShardIdSchema),
    shardIds: z.array(ShardIdSchema),
    shardsParentMap: z.union([z.record(z.string(), ShardIdSchema), z.null()]).optional(),
    shardsSplitMap: z.union([z.record(z.string(), z.array(ShardIdSchema)), z.null()]).optional(),
    version: z.number()
});
export const ShardUIdSchema = z.object({
    shardId: z.number(),
    version: z.number()
});
export const SignatureSchema = z.string();
export const SignedDelegateActionSchema = z.object({
    delegateAction: DelegateActionSchema,
    signature: SignatureSchema
});
export const SignedTransactionSchema = z.string();
export const SignedTransactionViewSchema = z.object({
    actions: z.array(ActionViewSchema),
    hash: CryptoHashSchema,
    nonce: z.number(),
    priorityFee: z.number(),
    publicKey: PublicKeySchema,
    receiverId: AccountIdSchema,
    signature: SignatureSchema,
    signerId: AccountIdSchema
});
export const SlashedValidatorSchema = z.object({
    accountId: AccountIdSchema,
    isDoubleSign: z.boolean()
});
export const StakeActionSchema = z.object({
    publicKey: PublicKeySchema,
    stake: z.string()
});
export const StateChangeCauseViewSchema = z.union([z.object({
    type: z.literal("not_writable_to_disk")
}), z.object({
    type: z.literal("initial_state")
}), z.object({
    txHash: CryptoHashSchema,
    type: z.literal("transaction_processing")
}), z.object({
    receiptHash: CryptoHashSchema,
    type: z.literal("action_receipt_processing_started")
}), z.object({
    receiptHash: CryptoHashSchema,
    type: z.literal("action_receipt_gas_reward")
}), z.object({
    receiptHash: CryptoHashSchema,
    type: z.literal("receipt_processing")
}), z.object({
    receiptHash: CryptoHashSchema,
    type: z.literal("postponed_receipt")
}), z.object({
    type: z.literal("updated_delayed_receipts")
}), z.object({
    type: z.literal("validator_accounts_update")
}), z.object({
    type: z.literal("migration")
}), z.object({
    type: z.literal("bandwidth_scheduler_state_update")
})]);
export const StateChangeKindViewSchema = z.union([z.object({
    accountId: AccountIdSchema,
    type: z.literal("account_touched")
}), z.object({
    accountId: AccountIdSchema,
    type: z.literal("access_key_touched")
}), z.object({
    accountId: AccountIdSchema,
    type: z.literal("data_touched")
}), z.object({
    accountId: AccountIdSchema,
    type: z.literal("contract_code_touched")
})]);
export const StateChangeWithCauseViewSchema = z.object({
    cause: StateChangeCauseViewSchema
}).and(z.union([z.object({
    change: z.object({
        accountId: AccountIdSchema,
        amount: z.string(),
        codeHash: CryptoHashSchema,
        globalContractAccountId: z.union([AccountIdSchema, z.null()]).optional(),
        globalContractHash: z.union([CryptoHashSchema, z.null()]).optional(),
        locked: z.string(),
        storagePaidAt: z.number(),
        storageUsage: z.number()
    }),
    type: z.literal("account_update")
}), z.object({
    change: z.object({
        accountId: AccountIdSchema
    }),
    type: z.literal("account_deletion")
}), z.object({
    change: z.object({
        accessKey: AccessKeyViewSchema,
        accountId: AccountIdSchema,
        publicKey: PublicKeySchema
    }),
    type: z.literal("access_key_update")
}), z.object({
    change: z.object({
        accountId: AccountIdSchema,
        publicKey: PublicKeySchema
    }),
    type: z.literal("access_key_deletion")
}), z.object({
    change: z.object({
        accountId: AccountIdSchema,
        gasKey: GasKeyViewSchema,
        publicKey: PublicKeySchema
    }),
    type: z.literal("gas_key_update")
}), z.object({
    change: z.object({
        accountId: AccountIdSchema,
        index: z.number(),
        nonce: z.number(),
        publicKey: PublicKeySchema
    }),
    type: z.literal("gas_key_nonce_update")
}), z.object({
    change: z.object({
        accountId: AccountIdSchema,
        publicKey: PublicKeySchema
    }),
    type: z.literal("gas_key_deletion")
}), z.object({
    change: z.object({
        accountId: AccountIdSchema,
        keyBase64: z.lazy(() => StoreKeySchema),
        valueBase64: z.lazy(() => StoreValueSchema)
    }),
    type: z.literal("data_update")
}), z.object({
    change: z.object({
        accountId: AccountIdSchema,
        keyBase64: z.lazy(() => StoreKeySchema)
    }),
    type: z.literal("data_deletion")
}), z.object({
    change: z.object({
        accountId: AccountIdSchema,
        codeBase64: z.string()
    }),
    type: z.literal("contract_code_update")
}), z.object({
    change: z.object({
        accountId: AccountIdSchema
    }),
    type: z.literal("contract_code_deletion")
})]));
export const StateItemSchema = z.object({
    key: z.lazy(() => StoreKeySchema),
    value: z.lazy(() => StoreValueSchema)
});
export const StateSyncConfigSchema = z.object({
    concurrency: z.lazy(() => SyncConcurrencySchema).optional(),
    dump: z.union([DumpConfigSchema, z.null()]).optional(),
    partsCompressionLvl: z.number(),
    sync: z.lazy(() => SyncConfigSchema).optional()
});
export const StatusSyncInfoSchema = z.object({
    earliestBlockHash: z.union([CryptoHashSchema, z.null()]).optional(),
    earliestBlockHeight: z.union([z.number(), z.null()]).optional(),
    earliestBlockTime: z.union([z.string(), z.null()]).optional(),
    epochId: z.union([EpochIdSchema, z.null()]).optional(),
    epochStartHeight: z.union([z.number(), z.null()]).optional(),
    latestBlockHash: CryptoHashSchema,
    latestBlockHeight: z.number(),
    latestBlockTime: z.string(),
    latestStateRoot: CryptoHashSchema,
    syncing: z.boolean()
});
export const StorageErrorSchema = z.union([z.literal("StorageInternalError"), z.object({
    MissingTrieValue: MissingTrieValueSchema
}), z.literal("UnexpectedTrieValue"), z.object({
    StorageInconsistentState: z.string()
}), z.object({
    FlatStorageBlockNotSupported: z.string()
}), z.object({
    MemTrieLoadingError: z.string()
})]);
export const StorageGetModeSchema = z.union([z.literal("FlatStorage"), z.literal("Trie")]);
export const StorageUsageConfigViewSchema = z.object({
    numBytesAccount: z.number(),
    numExtraBytesRecord: z.number()
});
export const StoreKeySchema = z.string();
export const StoreValueSchema = z.string();
export const SyncCheckpointSchema = z.union([z.literal("genesis"), z.literal("earliest_available")]);
export const SyncConcurrencySchema = z.object({
    apply: z.number(),
    applyDuringCatchup: z.number(),
    peerDownloads: z.number(),
    perShard: z.number()
});
export const SyncConfigSchema = z.union([z.literal("Peers"), z.object({
    ExternalStorage: ExternalStorageConfigSchema
})]);
export const Tier1ProxyViewSchema = z.object({
    addr: z.string(),
    peerId: PublicKeySchema
});
export const TrackedShardsConfigSchema = z.union([z.literal("NoShards"), z.object({
    Shards: z.array(ShardUIdSchema)
}), z.literal("AllShards"), z.object({
    ShadowValidator: AccountIdSchema
}), z.object({
    Schedule: z.array(z.array(ShardIdSchema))
}), z.object({
    Accounts: z.array(AccountIdSchema)
})]);
export const TransferActionSchema = z.object({
    deposit: z.string()
});
export const TxExecutionErrorSchema = z.union([z.object({
    ActionError: ActionErrorSchema
}), z.object({
    InvalidTxError: InvalidTxErrorSchema
})]);
export const TxExecutionStatusSchema = z.union([z.literal("NONE"), z.literal("INCLUDED"), z.literal("EXECUTED_OPTIMISTIC"), z.literal("INCLUDED_FINAL"), z.literal("EXECUTED"), z.literal("FINAL")]);
export const UseGlobalContractActionSchema = z.object({
    contractIdentifier: GlobalContractIdentifierSchema
});
export const ValidatorInfoSchema = z.object({
    accountId: AccountIdSchema
});
export const ValidatorKickoutReasonSchema = z.union([z.literal("_UnusedSlashed"), z.object({
    NotEnoughBlocks: z.object({
        expected: z.number(),
        produced: z.number()
    })
}), z.object({
    NotEnoughChunks: z.object({
        expected: z.number(),
        produced: z.number()
    })
}), z.literal("Unstaked"), z.object({
    NotEnoughStake: z.object({
        stakeU128: z.string(),
        thresholdU128: z.string()
    })
}), z.literal("DidNotGetASeat"), z.object({
    NotEnoughChunkEndorsements: z.object({
        expected: z.number(),
        produced: z.number()
    })
}), z.object({
    ProtocolVersionTooOld: z.object({
        networkVersion: z.number(),
        version: z.number()
    })
})]);
export const ValidatorKickoutViewSchema = z.object({
    accountId: AccountIdSchema,
    reason: ValidatorKickoutReasonSchema
});
export const ValidatorStakeViewSchema = z.object({
    validatorStakeStructVersion: z.literal("V1")
}).and(z.lazy(() => ValidatorStakeViewV1Schema));
export const ValidatorStakeViewV1Schema = z.object({
    accountId: AccountIdSchema,
    publicKey: PublicKeySchema,
    stake: z.string()
});
export const VersionSchema = z.object({
    build: z.string(),
    commit: z.string(),
    rustcVersion: z.string(),
    version: z.string()
});
export const ViewStateResultSchema = z.object({
    proof: z.array(z.string()).optional(),
    values: z.array(StateItemSchema)
});
export const VMConfigViewSchema = z.object({
    discardCustomSections: z.boolean(),
    ethImplicitAccounts: z.boolean(),
    extCosts: ExtCostsConfigViewSchema,
    fixContractLoadingCost: z.boolean(),
    globalContractHostFns: z.boolean(),
    growMemCost: z.number(),
    implicitAccountCreation: z.boolean(),
    limitConfig: LimitConfigSchema,
    reftypesBulkMemory: z.boolean(),
    regularOpCost: z.number(),
    saturatingFloatToInt: z.boolean(),
    storageGetMode: StorageGetModeSchema,
    vmKind: z.lazy(() => VMKindSchema)
});
export const VMKindSchema = z.union([z.literal("Wasmer0"), z.literal("Wasmtime"), z.literal("Wasmer2"), z.literal("NearVm"), z.literal("NearVm2")]);
export const WasmTrapSchema = z.union([z.literal("Unreachable"), z.literal("IncorrectCallIndirectSignature"), z.literal("MemoryOutOfBounds"), z.literal("CallIndirectOOB"), z.literal("IllegalArithmetic"), z.literal("MisalignedAtomicAccess"), z.literal("IndirectCallToNull"), z.literal("StackOverflow"), z.literal("GenericTrap")]);
export const WitnessConfigViewSchema = z.object({
    combinedTransactionsSizeLimit: z.number(),
    mainStorageProofSizeSoftLimit: z.number(),
    newTransactionsValidationStateSizeSoftLimit: z.number()
});
export const JsonRpcResponseForArrayOfRangeOfUint64AndRpcErrorResponseSchema = z.array(Range_of_uint64Schema);
export const JsonRpcResponseForArrayOfValidatorStakeViewAndRpcErrorResponseSchema = z.array(ValidatorStakeViewSchema);
export const JsonRpcResponseForNullableRpcHealthResponseAndRpcErrorResponseSchema = z.union([RpcHealthResponseSchema, z.null()]);
export const RpcStateChangesInBlockByTypeRequestAccountChangesSchema = z.union([z.object({
    blockId: BlockIdSchema
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("account_changes")
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("account_changes")
})), z.object({
    syncCheckpoint: SyncCheckpointSchema
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("account_changes")
}))]);
export const RpcStateChangesInBlockByTypeRequestSingleAccessKeyChangesSchema = z.union([z.object({
    blockId: BlockIdSchema
}).and(z.object({
    changesType: z.literal("single_access_key_changes"),
    keys: z.array(AccountWithPublicKeySchema)
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    changesType: z.literal("single_access_key_changes"),
    keys: z.array(AccountWithPublicKeySchema)
})), z.object({
    syncCheckpoint: SyncCheckpointSchema
}).and(z.object({
    changesType: z.literal("single_access_key_changes"),
    keys: z.array(AccountWithPublicKeySchema)
}))]);
export const RpcStateChangesInBlockByTypeRequestSingleGasKeyChangesSchema = z.union([z.object({
    blockId: BlockIdSchema
}).and(z.object({
    changesType: z.literal("single_gas_key_changes"),
    keys: z.array(AccountWithPublicKeySchema)
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    changesType: z.literal("single_gas_key_changes"),
    keys: z.array(AccountWithPublicKeySchema)
})), z.object({
    syncCheckpoint: SyncCheckpointSchema
}).and(z.object({
    changesType: z.literal("single_gas_key_changes"),
    keys: z.array(AccountWithPublicKeySchema)
}))]);
export const RpcStateChangesInBlockByTypeRequestAllAccessKeyChangesSchema = z.union([z.object({
    blockId: BlockIdSchema
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("all_access_key_changes")
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("all_access_key_changes")
})), z.object({
    syncCheckpoint: SyncCheckpointSchema
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("all_access_key_changes")
}))]);
export const RpcStateChangesInBlockByTypeRequestAllGasKeyChangesSchema = z.union([z.object({
    blockId: BlockIdSchema
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("all_gas_key_changes")
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("all_gas_key_changes")
})), z.object({
    syncCheckpoint: SyncCheckpointSchema
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("all_gas_key_changes")
}))]);
export const RpcStateChangesInBlockByTypeRequestContractCodeChangesSchema = z.union([z.object({
    blockId: BlockIdSchema
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("contract_code_changes")
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("contract_code_changes")
})), z.object({
    syncCheckpoint: SyncCheckpointSchema
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("contract_code_changes")
}))]);
export const RpcStateChangesInBlockByTypeRequestDataChangesSchema = z.union([z.object({
    blockId: BlockIdSchema
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("data_changes"),
    keyPrefixBase64: StoreKeySchema
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("data_changes"),
    keyPrefixBase64: StoreKeySchema
})), z.object({
    syncCheckpoint: SyncCheckpointSchema
}).and(z.object({
    accountIds: z.array(AccountIdSchema),
    changesType: z.literal("data_changes"),
    keyPrefixBase64: StoreKeySchema
}))]);
export const RpcQueryRequestViewAccountSchema = z.union([z.object({
    blockId: BlockIdSchema
}).and(z.object({
    accountId: AccountIdSchema,
    requestType: z.literal("view_account")
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    accountId: AccountIdSchema,
    requestType: z.literal("view_account")
})), z.object({
    syncCheckpoint: SyncCheckpointSchema
}).and(z.object({
    accountId: AccountIdSchema,
    requestType: z.literal("view_account")
}))]);
export const RpcQueryRequestViewCodeSchema = z.union([z.object({
    blockId: BlockIdSchema
}).and(z.object({
    accountId: AccountIdSchema,
    requestType: z.literal("view_code")
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    accountId: AccountIdSchema,
    requestType: z.literal("view_code")
})), z.object({
    syncCheckpoint: SyncCheckpointSchema
}).and(z.object({
    accountId: AccountIdSchema,
    requestType: z.literal("view_code")
}))]);
export const RpcQueryRequestViewStateSchema = z.union([z.object({
    blockId: BlockIdSchema
}).and(z.object({
    accountId: AccountIdSchema,
    includeProof: z.boolean().optional(),
    prefixBase64: StoreKeySchema,
    requestType: z.literal("view_state")
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    accountId: AccountIdSchema,
    includeProof: z.boolean().optional(),
    prefixBase64: StoreKeySchema,
    requestType: z.literal("view_state")
})), z.object({
    syncCheckpoint: SyncCheckpointSchema
}).and(z.object({
    accountId: AccountIdSchema,
    includeProof: z.boolean().optional(),
    prefixBase64: StoreKeySchema,
    requestType: z.literal("view_state")
}))]);
export const RpcQueryRequestViewAccessKeySchema = z.union([z.object({
    blockId: BlockIdSchema
}).and(z.object({
    accountId: AccountIdSchema,
    publicKey: PublicKeySchema,
    requestType: z.literal("view_access_key")
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    accountId: AccountIdSchema,
    publicKey: PublicKeySchema,
    requestType: z.literal("view_access_key")
})), z.object({
    syncCheckpoint: SyncCheckpointSchema
}).and(z.object({
    accountId: AccountIdSchema,
    publicKey: PublicKeySchema,
    requestType: z.literal("view_access_key")
}))]);
export const RpcQueryRequestViewAccessKeyListSchema = z.union([z.object({
    blockId: BlockIdSchema
}).and(z.object({
    accountId: AccountIdSchema,
    requestType: z.literal("view_access_key_list")
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    accountId: AccountIdSchema,
    requestType: z.literal("view_access_key_list")
})), z.object({
    syncCheckpoint: SyncCheckpointSchema
}).and(z.object({
    accountId: AccountIdSchema,
    requestType: z.literal("view_access_key_list")
}))]);
export const RpcQueryRequestCallFunctionSchema = z.union([z.object({
    blockId: BlockIdSchema
}).and(z.object({
    accountId: AccountIdSchema,
    argsBase64: FunctionArgsSchema,
    methodName: z.string(),
    requestType: z.literal("call_function")
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    accountId: AccountIdSchema,
    argsBase64: FunctionArgsSchema,
    methodName: z.string(),
    requestType: z.literal("call_function")
})), z.object({
    syncCheckpoint: SyncCheckpointSchema
}).and(z.object({
    accountId: AccountIdSchema,
    argsBase64: FunctionArgsSchema,
    methodName: z.string(),
    requestType: z.literal("call_function")
}))]);
export const RpcQueryRequestViewGlobalContractCodeSchema = z.union([z.object({
    blockId: BlockIdSchema
}).and(z.object({
    codeHash: CryptoHashSchema,
    requestType: z.literal("view_global_contract_code")
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    codeHash: CryptoHashSchema,
    requestType: z.literal("view_global_contract_code")
})), z.object({
    syncCheckpoint: SyncCheckpointSchema
}).and(z.object({
    codeHash: CryptoHashSchema,
    requestType: z.literal("view_global_contract_code")
}))]);
export const RpcQueryRequestViewGlobalContractCodeByAccountIdSchema = z.union([z.object({
    blockId: BlockIdSchema
}).and(z.object({
    accountId: AccountIdSchema,
    requestType: z.literal("view_global_contract_code_by_account_id")
})), z.object({
    finality: FinalitySchema
}).and(z.object({
    accountId: AccountIdSchema,
    requestType: z.literal("view_global_contract_code_by_account_id")
})), z.object({
    syncCheckpoint: SyncCheckpointSchema
}).and(z.object({
    accountId: AccountIdSchema,
    requestType: z.literal("view_global_contract_code_by_account_id")
}))]);
