import { buildMappedProperties } from "../../src/builder/build-mapped-properties";

describe("Build Mapped Properties", () => {
  it("should build mapped properties text", () => {
    const fixture = {
      expect: `/**
 * THIS FILE IS GENERATED - DO NOT MODIFY DIRECTLY
 * Generated by @saka-labsonrpc/jsonrpc-generator
 * 
 * @generated
 */
export const mappedSnakeCamelProperty = new Map<string, string>([["hello_world", "helloWorld"],
["hello_world_2", "helloWorld2"],
["hello_world_3", "helloWorld3"],
["hello_world_4", "helloWorld4"]]);
`,
    };

    const mappedSnakeCamelProperty = new Map<string, string>([
      ["hello_world", "helloWorld"],
      ["hello_world_2", "helloWorld2"],
      ["hello_world_3", "helloWorld3"],
      ["hello_world_4", "helloWorld4"],
    ]);
    const result = buildMappedProperties(mappedSnakeCamelProperty);
    expect(result).toBe(fixture.expect);
  });
});
