import { buildSchemas } from "../../src/builder/build-schemas";
import { SchemaType } from "../../src/types";

describe("Build Schemas", () => {
  it("should build schemas text", () => {
    const fixture = {
      expect: `/**
 * THIS FILE IS GENERATED - DO NOT MODIFY DIRECTLY
 * Generated by @saka-labsonrpc/jsonrpc-generator with credit to openapi-typescript <3
 * 
 * @generated
 */
export type Foo = { foo: string, bar: number, baz: boolean, qux: string[], quux: { quuz: string } };
export type Bar = { bar: number };
`,
    };

    const schemaTypes: SchemaType[] = [
      {
        schema: "Foo",
        type: "{ foo: string, bar: number, baz: boolean, qux: string[], quux: { quuz: string } }",
      },
      {
        schema: "Bar",
        type: "{ bar: number }",
      },
    ];

    const result = buildSchemas(schemaTypes);
    expect(result).toBe(fixture.expect);
  });
});
